name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request: # for new branches
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest #VM 
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: | #lint
          python -m pip ins tall --upgrade pip
          pip install ruff 
          
      - name: Run Ruff Linter
        run: ruff check --output-format=github . # user-friendly output for GIT